function fetchReports() {
    const reportsTableBody = document.getElementById('reportsTableBody');
    if (!reportsTableBody) return;

    fetch('../apis/reports-api.php?action=getAll')
        .then(res => res.json())
        .then(data => {
            reportsTableBody.innerHTML = '';
            data.forEach(report => {
                let actions = [];
                actions.push({
                    type: 'view',
                    label: 'View Details',
                    onclick: `viewReport(${report.id}); actionDropdown.closeAll();`
                });

                if (window.userRole === 'admin') {
                    actions.push({
                        type: 'delete',
                        label: 'Delete Report',
                        onclick: `confirmDelete(${report.id}, 'report', () => deleteReport(${report.id})); actionDropdown.closeAll();`
                    });
                }

                if(window.userRole==='cashier')
                {
                     actions.push({
                        type: 'print',
                        label: 'Print Report',
                        onclick: `printReport(${report.id}); actionDropdown.closeAll();`
                    });
                }

                const actionDropdownHTML = actionDropdown.createDropdown(actions);
    reportsTableBody.innerHTML += `
        <tr>
                    <td>#${report.id}</td>
                    <td>${report.type}</td>
                    <td>${new Date(report.start_date).toLocaleDateString()} - ${new Date(report.end_date).toLocaleDateString()}</td>
                    <td>${new Date(report.created_at).toLocaleDateString()}</td>
                    <td>${report.generated_by || 'System'}</td> 
                    <td>${actionDropdownHTML}</td>
                </tr>
    `;
});
        })
        .catch(err => console.error('Error fetching reports:', err));
}

function generateReport() {
    const type = document.getElementById('reportType').value;
    const dateRange = document.getElementById('dateRange').value;
    
    // The dateRange is now guaranteed to be one of the generalized options (today, week, etc.)
    const dataToSend = {
        type: type,
        dateRange: dateRange
    };
    
    fetch('../apis/reports-api.php?action=generate', {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify(dataToSend)
    })
    .then(res => res.json())
    .then(result => {
        if (result.success) {
            showToast('Report generated successfully', 'success');
            fetchReports();
        } else {
            showToast(result.message, 'error');
        }
    })
    .catch(err => showToast('An error occurred generating the report.', 'error'));
}

function viewReport(id) {
    fetch(`../apis/reports-api.php?action=getById&id=${id}`)
        .then(res => res.json())
        .then(report => {
            document.getElementById('viewModalTitle').innerText = 'Report Details';
            document.getElementById('viewModalBody').innerHTML = `
                <p><strong>ID:</strong> #${report.id}</p>
                <p><strong>Type:</strong> ${report.type}</p>
                <p><strong>Date Range:</strong> ${new Date(report.start_date).toLocaleDateString()} - ${new Date(report.end_date).toLocaleDateString()}</p>
                <p><strong>Generated On:</strong> ${new Date(report.created_at).toLocaleString()}</p>
                <p><strong>Generated By:</strong> ${report.generated_by || 'System'}</p>
            `;
            openModal('viewModal');
        });
}

function deleteReport(id) {
    fetch(`../apis/reports-api.php?action=delete&id=${id}`)
        .then(res => res.json())
        .then(result => {
            if (result.success) {
                showToast(result.message, 'success');
                closeModal('deleteModal');
                fetchReports();
            } else {
                showToast(result.message, 'error');
                closeModal('deleteModal');
            }
        })
        .catch(err => showToast('An error occurred while deleting the report.', 'error'));
}

function downloadReport(id) {
    window.open(`../apis/reports-api.php?action=download&id=${id}`, '_blank');
}

function printReport(id) {
    const printWindow = window.open(`../apis/reports-api.php?action=print&id=${id}`, '_blank', 'width=1000,height=800');
    
    if (printWindow) {
        printWindow.focus();
    }
}

document.addEventListener('DOMContentLoaded', () => {
    fetchReports();
});

window.fetchReports = fetchReports;
window.generateReport = generateReport;
window.viewReport = viewReport;
window.downloadReport = downloadReport;
window.printReport = printReport;